# {dotfiles}/bombadil.toml

# Path to your dotfiles relative to your $HOME directory
dotfiles_dir = "sources/dotfiles"

[settings]
# An array of toml files paths containing the variables to inject in your templatized dotfiles
# You can have multiple var files as long as variable names does not colide.
vars = [ "vars.toml" ]

[settings.dots]

# A dot entry representing a symlink, `source` is relative to `dotfiles_dir`
# and `target` shall be relative to $HOME directory or absolute.
alacritty = { source = "alacritty", target = ".config/alacritty" }
betterdiscord = { source = "betterdiscord", target = ".config/BetterDiscord" }
fontconfig = { source = "fontconfig", target = ".config/fontconfig" }
gtk3 = { source = "gtk/gtk-3.0", target = ".config/gtk-3.0" }
kitty = { source = "kitty", target = ".config/kitty" }
nvim = { source = "nvim", target = ".config/nvim" }
mpd = { source = "mpd", target = ".config/mpd" }
mpv = { source = "mpv", target = ".config/mpv" }
ncmpcpp = { source = "ncmpcpp", target = ".config/ncmpcpp" }
neofetch = { source = "neofetch", target = ".config/neofetch" }
ranger = { source = "ranger", target = ".config/ranger" }
redshift = { source = "redshift", target = ".config/redshift" }
wal = { source = "wal", target = ".config/wal" }
zathura = { source = "zathura", target = ".config/zathura" }

cpxc = { source = "scripts/connect_pxc.sh", target = "scripts/connect_pxc.sh" }
dpxc = { source = "scripts/disconnect_pxc.sh", target = "scripts/disconnect_pxc.sh" }
osh = { source = "scripts/osuhelper.sh", target = "scripts/osuhelper.sh" }
ppxc = { source = "scripts/pair_pxc.sh", target = "scripts/pair_pxc.sh" }
pyps = { source = "scripts/pyps.sh", target = "scripts/pyps.sh" }
rea = { source = "scripts/rearchive.sh", target = "scripts/rearchive.sh" }
setbg = { source = "scripts/setbg.sh", target = "scripts/setbg.sh" }
xauto = { source = "scripts/xautostart.sh", target = "scripts/xautostart.sh" }
xev = { source = "scripts/xev.sh", target = "scripts/xev.sh" }
ycmd = { source = "scripts/ycmd.sh", target = "scripts/ycmd.sh" }
yt = { source = "scripts/yt.sh", target = "scripts/yt.sh" }
ytarchive = { source = "scripts/ytarchive.sh", target = "scripts/ytarchive.sh" }
ytaudio = { source = "scripts/ytaudio.sh", target = "scripts/ytaudio.sh" }

xdg = { source = "xdg/user-dirs.dirs", target = ".config/user-dirs.dirs" }
gitconfig = { source = "git/.gitconfig", target = ".gitconfig" }
gtk2 = { source = "gtk/.gtkrc-2.0", target = ".gtkrc-2.0" }
zprofile = { source = "zsh/.zprofile", target = ".zprofile" }
zshrc = { source = "zsh/.zshrc", target = ".zshrc" }


[profiles.bspwm]

posthooks = [ "bspc wm -r" ]

[profiles.bspwm.dots]
bspwm = { source = "bspwm", target = ".config/bspwm" }
flameshot = { source = "flameshot", target = ".config/flameshot" }
polybar = { source = "polybar", target = ".config/polybar" }
rofi = { source = "rofi", target = ".config/rofi" }
sxhkd = { source = "sxhkd", target = ".config/sxhkd" }

betterlockscreen = { source = "betterlockscreen/betterlockscreenrc", target = ".config/betterlockscreenrc" }
picom = { source = "picom/picom.conf", target = ".config/picom.conf" }
screenlayout = { source = "screenlayout", target = ".screenlayout" }
xinitrc = { source = "x11/.xinitrc", target = ".xinitrc" }
xmodmap = { source = "x11/.Xmodmap", target = ".Xmodmap" }
