wm = "bspwm"
setup = "college"
main_monitor = "DP-4"
r_monitor = "DP-2" 
l_monitor = "DP-1"
wallpaper = "~/dotfiles/assets/wallpapers/icpcbg.png"
wal = "~/dotfiles/wal/backup"
use_xrandr = "true"
xrandr_script = "~/dotfiles/screenlayout/college.sh"
using_displaycal = "false"
