wm = "bspwm"
setup = "college"

main_monitor = "DP-2"
l_monitor = "HDMI-0"
r_monitor = "DP-4" 
use_main = "true"
use_l = "true"
use_r = "false"

wallpaper = "/home/neil/pictures/anime/wallpapers/wallpaper-low-exposure.png"
wal = "~/.config/wal/backup"
use_xrandr = "true"
xrandr_script = "~/.screenlayout/gatech.sh"

