--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/neil/pictures/anime/wallpapers/88876556.jpg"

-- Special
background="#0b0822"
foreground="#e8ddd1"
cursor="#e8ddd1"

-- Colors
color0="#0b0822"
color1="#5F4A65"
color2="#A9344D"
color3="#8B4865"
color4="#93518B"
color5="#E4579B"
color6="#698EA9"
color7="#e8ddd1"
color8="#a29a92"
color9="#5F4A65"
color10="#A9344D"
color11="#8B4865"
color12="#93518B"
color13="#E4579B"
color14="#698EA9"
color15="#e8ddd1"
