#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc rule -r "*"

bspc wm -O {{ main_monitor }}

bspc monitor {{ main_monitor }} -d 1 2 3 4 5
bspc monitor {{ l_monitor }} -d 6 7 8 9 10
# bspc monitor {{ r_monitor }} -d 11 12 13 14 15


bspc config window_gap          15

bspc config top_padding 50
bspc config bottom_padding 10
bspc config left_padding 10
bspc config right_padding 10

bspc config border_width         4
bspc config focused_border_color "#93518B"
bspc config active_border_color "#5F4A65"
bspc config normal_border_color "#5F4A65"

# bspc config border_width 14
# bspc config normal_border_color       '#000000'
# bspc config active_border_color       '#000000'
# bspc config focused_border_color      '#000000'

bspc config ignore_ewmh_focus true

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config pointer_motion_interval 7ms
bspc config focus_follows_pointer true
bspc config pointer_follows_focus true
bspc config pointer_follows_monitor true

~/.config/bspwm/windowrules.sh 
~/.config/bspwm/autostart.sh
# ~/.config/bspwm/2bspwm
