#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc rule -r "*"


{% if "home" in profiles %}

bspc wm -O {{ monitor.left }} {{ monitor.wide }} {{ monitor.main }}

bspc monitor {{ monitor.left }} -d 1 2 3 4 5
bspc monitor {{ monitor.wide }} -d 6 7 8 9 10
bspc monitor {{ monitor.main }} -d 11 12 13 14 15

{% elif "edward" in profiles %}

bspc wm -O {{ monitor.wide }} {{ monitor.main }}

bspc monitor {{ monitor.wide }} -d 1 2 3 4 5
bspc monitor {{ monitor.main }} -d 6 7 8 9 10

{% elif "laptop" in profiles %}

bspc wm -O {{ monitor.main }}

{% if "displaylink2" in profiles %}

bspc monitor {{ monitor.main}} -d 1 2 3 4 5
bspc monitor {{ monitor.left }} -d 6 7 8 9 10

{% elif "displaylink3" in profiles %}

bspc monitor {{ monitor.main }} -d 1 2 3 4 5
bspc monitor {{ monitor.left }} -d 6 7 8 9 10
bspc monitor {{ monitor.right }} -d 11 12 13 14 15

{% else %}
# base laptop

bspc monitor {{ monitor.main }} -d 1 2 3 4 5 6 7 8 9 10

{% endif %}

{% else %}
# desktop

bspc wm -O {{ monitor.main }}

bspc monitor {{ monitor.main }} -d 1 2 3 4 5
bspc monitor {{ monitor.left }} -d 6 7 8 9 10

{% endif %}


bspc config border_width         {{ bspwm.border_width }}

bspc config window_gap          {{ bspwm.window_gap }}

bspc config top_padding {{ bspwm.top_padding }}
bspc config bottom_padding {{ bspwm.bottom_padding }}
bspc config left_padding {{ bspwm.left_padding }}
bspc config right_padding {{ bspwm.right_padding }}

# source pywal palette so borders track the wallpaper theme
. "$HOME/.cache/wal/colors.sh"
bspc config focused_border_color "$color5"
bspc config active_border_color  "$color4"
bspc config normal_border_color  "$color1"

bspc config ignore_ewmh_focus true

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config pointer_motion_interval 7ms
bspc config focus_follows_pointer true
bspc config pointer_follows_focus true
bspc config pointer_follows_monitor true

$HOME/.config/bspwm/windowrules.sh 
$HOME/.config/bspwm/autostart.sh
