#!/bin/sh
# neeasade
# makes dual borders
# depends on wmutils/opt

focused_window() {
  bspc query -N -n .focused
}

active_windows() {
  bspc query -N -n .!descendant_of.window
}

# echo focused window
# echo $(focused_window)
#
# echo 
# echo active windows 
# echo $(active_windows)


border_width_current=$(bspc config border_width)

# half if even, 1px to outer if odd
# border_width_in_normal=$(( border_width_current/2 ))
# border_width_out_normal=$(( (border_width_current/2) + (border_width_current%2) ))


border_width_in_normal=4
border_width_out_normal=10
border_width_in_focused=$border_width_in_normal
border_width_out_focused=$border_width_out_normal

border_color_in_normal=5F4A65
border_color_in_focused=93518B

border_color_out_normal=0B0822
border_color_out_focused=0B0822




_chwb2() {
    colorType=$1
    shift
    _getVal() {
	eval echo \$${1}_${colorType}
    }

    [ "$width_normal" = "$width_focused" ] || \
	echo "$@" | sed 's/ /\n/g' | xargs -I{} bspc config -n {} border_width $(_getVal width)

    chwb2 -I $(_getVal border_color_in) -O $(_getVal border_color_out) -i $(_getVal border_width_in) -o $(_getVal border_width_out) $@ 2>/dev/null
}

width_normal=$((border_width_in_normal+border_width_out_normal))
width_focused=$((border_width_in_focused+border_width_out_focused))
bspc config border_width "$width_normal"

_chwb2 focused $(focused_window)
_chwb2 normal $(active_windows)

bspc subscribe node_state node_geometry node_focus | while read msg; do
    _chwb2 focused $(focused_window)
    _chwb2 normal $(active_windows)
done
