#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc rule -r "*"

bspc wm -O HDMI-0 DP-4 DP-2

bspc monitor HDMI-0 -d 2 5 8 
bspc monitor DP-4   -d 1 4 7
bspc monitor DP-2   -d 3 6 9

bspc config window_gap          40
# bspc config -m HDMI-0 top_padding 18
# bspc config -m DP-4 top_padding 25
# bspc config -m DP-2 top_padding 18

bspc config top_padding 50
bspc config bottom_padding 30
bspc config left_padding 30
bspc config right_padding 30

# bspc config border_width         2
# bspc config focused_border_color "#93518B"
# bspc config active_border_color "#5F4A65"
# bspc config normal_border_color "#5F4A65"

# to prevent double border from being weird (need a permanent fix though)
bspc config normal_border_color       '#000000'
bspc config active_border_color       '#000000'
bspc config focused_border_color      '#000000'
bspc config border_width 14

# bspc config ignore_ewmh_fullscreen all
bspc config ignore_ewmh_focus true

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config pointer_motion_interval 7ms
bspc config focus_follows_pointer true
bspc config pointer_follows_focus true
bspc config pointer_follows_monitor true

~/.config/bspwm/windowrules.sh

~/.config/bspwm/autostart.sh
