;; ┌────────────────────────────────────────────────────────────┐
;; │░█▀█░█▀█░█░░░█░█░█▀▄░█▀█░█▀▄░░░░░░░░░█▀▀░█▀█░█▀█░█▀▀░▀█▀░█▀▀│
;; │░█▀▀░█░█░█░░░░█░░█▀▄░█▀█░█▀▄░░░░▀░░░░█░░░█░█░█░█░█▀▀░░█░░█░█│
;; │░▀░░░▀▀▀░▀▀▀░░▀░░▀▀░░▀░▀░▀░▀░░░░▀░░░░▀▀▀░▀▀▀░▀░▀░▀░░░▀▀▀░▀▀▀│
;; │░Created░By░Aditya░Shakya░@adi1090x░░░░░░░░░░░░░░░░░░░░░░░░░│
;; └────────────────────────────────────────────────────────────┘

;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_


; colors sourced from pywal (see ~/.config/wal/templates/colors-polybar.ini)
include-file = ~/.cache/wal/colors-polybar.ini

;; Global WM Settings

[global/wm]
margin-bottom = 0

margin-top = 0

include-file = ~/.config/polybar/modules.ini


;; Bar Settings
[bar/main]
monitor-fallback =
monitor-strict = true
override-redirect = true
bottom = false
fixed-center = true

background = #ff15080f
foreground = ${color.foreground}

line-size = 2
line-color = ${color.accent}

border-color = ${color.accent}
border-bottom-size = 1
border-left-size = 1
border-right-size = 1
border-top-size = 1

offset-y = 12

padding-left = 2
padding-right = 2

module-margin-left = 1
module-margin-right = 1

separator = "·"
separator-foreground = ${color.foreground-alt}

radius-top = 10.0
radius-bottom = 10.0

font-0 = "JetBrainsMono Nerd Font:size=10;3"
font-1 = "JetBrainsMono Nerd Font:size=11;3"

wm-name = bspwm

dim-value = 1.0

tray-position = none
tray-detached = false
tray-maxsize = 16
tray-background = ${color.background}
tray-offset-x = 0
tray-offset-y = 0
tray-padding = 0
tray-scale = 1.0
wm-restack = bspwm

enable-ipc = true

[bar/center]
; change this depending on when im at home/college
; TODO
{% if "home" in profiles or "edward" in profiles %}
monitor = {{ monitor.wide }}
{% else %}
monitor = {{ monitor.main }}
{% endif %}

{% if "home" in profiles %}

modules-left = visualizer nowplaying
modules-center = workspaces
modules-right = battery pulseaudio bluetooth network date sysmenu

{% elif "edward" in profiles %}

modules-left = visualizer nowplaying
modules-center = workspaces
modules-right = battery pulseaudio bluetooth network date sysmenu

{% elif "laptop" in profiles %}

modules-left = visualizer nowplaying
modules-center = workspaces
modules-right = battery pulseaudio bluetooth network date sysmenu

{% else %}

modules-left = visualizer nowplaying
modules-center = workspaces
modules-right = pulseaudio bluetooth network date sysmenu

{% endif %}


inherit= bar/main

width = 80%
height = 30

offset-x = 10%

padding-left = 4

{% if "displaylink2" in profiles or "displaylink3" in profiles or "desktop" in profiles or "home" in profiles %}
[bar/left]
monitor = {{ monitor.left }}
modules-left = visualizer
modules-center = workspaces
inherit= bar/main

width = 60%
height = 30

offset-x = 20%
{% endif %}

{% if "displaylink3" in profiles or "desktop" in profiles %}
[bar/right]
monitor = {{ monitor.right }}
modules-left = visualizer
modules-center = workspaces
inherit= bar/main

width = 60%
height = 30

offset-x = 20%
{% endif %}

{% if "home" in profiles or "edward" in profiles %}
[bar/right]
monitor = {{ monitor.main }}
modules-left = visualizer
modules-center = workspaces
inherit= bar/main

width = 60%
height = 30

offset-x = 20%
{% endif %}




[settings]
; The throttle settings lets the eventloop swallow up til X events
; if they happen within Y millisecond after first event was received.
; This is done to prevent flood of update event.
;
; For example if 5 modules emit an update event at the same time, we really
; just care about the last one. But if we wait too long for events to swallow
; the bar would appear sluggish so we continue if timeout
; expires or limit is reached.
throttle-output = 5
throttle-output-for = 10

; Time in milliseconds that the input handler will wait between processing events
;throttle-input-for = 30

; Reload upon receiving XCB_RANDR_SCREEN_CHANGE_NOTIFY events
screenchange-reload = false

; Compositing operators
; @see: https://www.cairographics.org/manual/cairo-cairo-t.html#cairo-operator-t
compositing-background = source
compositing-foreground = over
compositing-overline = over
compositing-underline = over
compositing-border = over

; Define fallback values used by all module formats
;format-foreground = 
;format-background = 
;format-underline =
;format-overline =
;format-spacing =
;format-padding =
;format-margin =
;format-offset =

; Enables pseudo-transparency for the bar
; If set to true the bar can be transparent without a compositor.
pseudo-transparency = false

;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

