# Shell variables
# Generated by 'wal'
wallpaper='/home/neil/downloads/88876556.jpg'

# Special
background='#0b0822'
foreground='#e8ddd1'
cursor='#e8ddd1'

# Colors
color0='#0b0822'
color1='#5F4A65'
color2='#A9344D'
color3='#8B4865'
color4='#93518B'
color5='#E4579B'
color6='#698EA9'
color7='#e8ddd1'
color8='#a29a92'
color9='#5F4A65'
color10='#A9344D'
color11='#8B4865'
color12='#93518B'
color13='#E4579B'
color14='#698EA9'
color15='#e8ddd1'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
